(define (min x y z)
    (cond ((and (< x y) (< x z)) x)
          ((and (< y x) (< y z)) y)
          ((and (< z x) (< z y)) z)))
(define (sqr x y)
    (+ (* x x) (* y y))) 
(define (sum-of-squares-of-top-two x y z)
    (cond ((= (min x y z) x) (sqr y z))
          ((= (min x y z) y) (sqr x z))
          ((= (min x y z) z) (sqr x y))))
